# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/koputo/escada2-core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/koputo/escada2-core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/koputo/escada2-core/CMakeFiles /home/koputo/escada2-core/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/koputo/escada2-core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named escada_core

# Build rule for target.
escada_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 escada_core
.PHONY : escada_core

# fast build rule for target.
escada_core/fast:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/build
.PHONY : escada_core/fast

#=============================================================================
# Target rules for targets named zigbeemtm

# Build rule for target.
zigbeemtm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zigbeemtm
.PHONY : zigbeemtm

# fast build rule for target.
zigbeemtm/fast:
	$(MAKE) -f external/zigbeemtm/CMakeFiles/zigbeemtm.dir/build.make external/zigbeemtm/CMakeFiles/zigbeemtm.dir/build
.PHONY : zigbeemtm/fast

TypeThread.o: TypeThread.cpp.o
.PHONY : TypeThread.o

# target to build an object file
TypeThread.cpp.o:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/TypeThread.cpp.o
.PHONY : TypeThread.cpp.o

TypeThread.i: TypeThread.cpp.i
.PHONY : TypeThread.i

# target to preprocess a source file
TypeThread.cpp.i:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/TypeThread.cpp.i
.PHONY : TypeThread.cpp.i

TypeThread.s: TypeThread.cpp.s
.PHONY : TypeThread.s

# target to generate assembly for a file
TypeThread.cpp.s:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/TypeThread.cpp.s
.PHONY : TypeThread.cpp.s

dbase.o: dbase.cpp.o
.PHONY : dbase.o

# target to build an object file
dbase.cpp.o:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/dbase.cpp.o
.PHONY : dbase.cpp.o

dbase.i: dbase.cpp.i
.PHONY : dbase.i

# target to preprocess a source file
dbase.cpp.i:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/dbase.cpp.i
.PHONY : dbase.cpp.i

dbase.s: dbase.cpp.s
.PHONY : dbase.s

# target to generate assembly for a file
dbase.cpp.s:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/dbase.cpp.s
.PHONY : dbase.cpp.s

drivers/MtmZigbee.o: drivers/MtmZigbee.cpp.o
.PHONY : drivers/MtmZigbee.o

# target to build an object file
drivers/MtmZigbee.cpp.o:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/drivers/MtmZigbee.cpp.o
.PHONY : drivers/MtmZigbee.cpp.o

drivers/MtmZigbee.i: drivers/MtmZigbee.cpp.i
.PHONY : drivers/MtmZigbee.i

# target to preprocess a source file
drivers/MtmZigbee.cpp.i:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/drivers/MtmZigbee.cpp.i
.PHONY : drivers/MtmZigbee.cpp.i

drivers/MtmZigbee.s: drivers/MtmZigbee.cpp.s
.PHONY : drivers/MtmZigbee.s

# target to generate assembly for a file
drivers/MtmZigbee.cpp.s:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/drivers/MtmZigbee.cpp.s
.PHONY : drivers/MtmZigbee.cpp.s

drivers/mercury230.o: drivers/mercury230.cpp.o
.PHONY : drivers/mercury230.o

# target to build an object file
drivers/mercury230.cpp.o:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/drivers/mercury230.cpp.o
.PHONY : drivers/mercury230.cpp.o

drivers/mercury230.i: drivers/mercury230.cpp.i
.PHONY : drivers/mercury230.i

# target to preprocess a source file
drivers/mercury230.cpp.i:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/drivers/mercury230.cpp.i
.PHONY : drivers/mercury230.cpp.i

drivers/mercury230.s: drivers/mercury230.cpp.s
.PHONY : drivers/mercury230.s

# target to generate assembly for a file
drivers/mercury230.cpp.s:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/drivers/mercury230.cpp.s
.PHONY : drivers/mercury230.cpp.s

function.o: function.cpp.o
.PHONY : function.o

# target to build an object file
function.cpp.o:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/function.cpp.o
.PHONY : function.cpp.o

function.i: function.cpp.i
.PHONY : function.i

# target to preprocess a source file
function.cpp.i:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/function.cpp.i
.PHONY : function.cpp.i

function.s: function.cpp.s
.PHONY : function.s

# target to generate assembly for a file
function.cpp.s:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/function.cpp.s
.PHONY : function.cpp.s

kernel.o: kernel.cpp.o
.PHONY : kernel.o

# target to build an object file
kernel.cpp.o:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/kernel.cpp.o
.PHONY : kernel.cpp.o

kernel.i: kernel.cpp.i
.PHONY : kernel.i

# target to preprocess a source file
kernel.cpp.i:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/kernel.cpp.i
.PHONY : kernel.cpp.i

kernel.s: kernel.cpp.s
.PHONY : kernel.s

# target to generate assembly for a file
kernel.cpp.s:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/kernel.cpp.s
.PHONY : kernel.cpp.s

logs.o: logs.cpp.o
.PHONY : logs.o

# target to build an object file
logs.cpp.o:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/logs.cpp.o
.PHONY : logs.cpp.o

logs.i: logs.cpp.i
.PHONY : logs.i

# target to preprocess a source file
logs.cpp.i:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/logs.cpp.i
.PHONY : logs.cpp.i

logs.s: logs.cpp.s
.PHONY : logs.s

# target to generate assembly for a file
logs.cpp.s:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/logs.cpp.s
.PHONY : logs.cpp.s

tinyxml2.o: tinyxml2.cpp.o
.PHONY : tinyxml2.o

# target to build an object file
tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/tinyxml2.cpp.o
.PHONY : tinyxml2.cpp.o

tinyxml2.i: tinyxml2.cpp.i
.PHONY : tinyxml2.i

# target to preprocess a source file
tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/tinyxml2.cpp.i
.PHONY : tinyxml2.cpp.i

tinyxml2.s: tinyxml2.cpp.s
.PHONY : tinyxml2.s

# target to generate assembly for a file
tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/escada_core.dir/build.make CMakeFiles/escada_core.dir/tinyxml2.cpp.s
.PHONY : tinyxml2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... escada_core"
	@echo "... rebuild_cache"
	@echo "... zigbeemtm"
	@echo "... TypeThread.o"
	@echo "... TypeThread.i"
	@echo "... TypeThread.s"
	@echo "... dbase.o"
	@echo "... dbase.i"
	@echo "... dbase.s"
	@echo "... drivers/MtmZigbee.o"
	@echo "... drivers/MtmZigbee.i"
	@echo "... drivers/MtmZigbee.s"
	@echo "... drivers/mercury230.o"
	@echo "... drivers/mercury230.i"
	@echo "... drivers/mercury230.s"
	@echo "... function.o"
	@echo "... function.i"
	@echo "... function.s"
	@echo "... kernel.o"
	@echo "... kernel.i"
	@echo "... kernel.s"
	@echo "... logs.o"
	@echo "... logs.i"
	@echo "... logs.s"
	@echo "... tinyxml2.o"
	@echo "... tinyxml2.i"
	@echo "... tinyxml2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

